version: "3.8"

services:
  haystack-api:
    image: renatojobal/maulli3-api:latest
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - DOCUMENTSTORE_PARAMS_HOST=elasticsearch
      - PIPELINE_YAML_PATH=/app/main_rest_api/pipeline/pipelines.haystack-pipeline.yml
      - TOKENIZERS_PARALLELISM=false
      - LOG_LEVEL=INFO
      - HAYSTACK_TELEMETRY_ENABLED=false
    command: gunicorn main_rest_api.application:app -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.6"
    ports:
      - 9200:9200
    restart: on-failure
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g # Ajusta según sea necesario
    healthcheck:
      test: curl --fail http://localhost:9200/_cat/health || exit 1
      interval: 10s
      timeout: 1s
      retries: 10
